code = (
    "package com.tilawa.sourate;\n"
    "import com.getcapacitor.BridgeActivity;\n"
    "import android.os.Bundle;\n"
    "import android.webkit.PermissionRequest;\n"
    "import android.webkit.WebChromeClient;\n"
    "import android.webkit.WebView;\n"
    "import app.capgo.speechrecognition.SpeechRecognitionPlugin;\n"
    "public class MainActivity extends BridgeActivity {\n"
    "    @Override\n"
    "    public void onCreate(Bundle savedInstanceState) {\n"
    "        registerPlugin(SpeechRecognitionPlugin.class);\n"
    "        super.onCreate(savedInstanceState);\n"
    "        WebView webView = getBridge().getWebView();\n"
    "        webView.setWebChromeClient(new WebChromeClient() {\n"
    "            @Override\n"
    "            public void onPermissionRequest(PermissionRequest request) {\n"
    "                request.grant(request.getResources());\n"
    "            }\n"
    "        });\n"
    "    }\n"
    "}\n"
)
open('android/app/src/main/java/com/tilawa/sourate/MainActivity.java', 'w').write(code)
