name: Generate Keystore
on: [workflow_dispatch]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkey -v -keystore tilawa.jks -alias tilawa -keyalg RSA -keysize 2048 -validity 10000 -storepass tilawa123 -keypass tilawa123 -dname "CN=Tilawa,O=Tilawa,C=DZ"
          echo "=== KEYSTORE BASE64 ==="
          base64 -w 0 tilawa.jks
          echo ""
          echo "=== FIN ==="
