name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22 }
      - name: Create Project
        run: |
          # Préparation web
          mkdir -p www
          cp index.html www/
          # Création du projet Capacitor
          npm init -y
          npm install @capacitor/core @capacitor/cli @capacitor/android @capacitor-community/speech-recognition
          npx cap init "Tilawa" "com.tilawa.sourate" --web-dir www
          npx cap add android
      - name: Upload Project
        uses: actions/upload-artifact@v4
        with:
          name: mon-projet-android
          path: android/
